spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: ${SPRING_APPLICATION_NAME:eveng}
  data:
    mongodb:
      uri: mongodb://${MONGO_URI:localhost}:27017/evengdatabase
  banner:
    charset: UTF-8
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
#  resources:
#    add-mappings: false

server:
  servlet:
    context-path: /
  port: ${TOMCAT_PORT:30001}
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: false




